[package]
name = "successugochukwuchi/colearn"
version = "0.1.0"
description = "CoLearn Student Portal"

[[module]]
name = "server"
source = "wasmer/static-server"

[[command]]
name = "serve"
module = "server"
runner = "https://webc.org/runner/wasi"

[command.annotations]
wasi = { args = ["--directory", "dist", "--spa"], main-args = ["--directory", "dist", "--spa"] }
