export const DEPARTMENTS = [
  "Agribusiness",
  "Agricultural and Bio resources Engineering",
  "Agricultural Economics",
  "Agricultural Extension",
  "Animal Science and Technology",
  "Architecture",
  "Biochemistry",
  "Biomedical Engineering",
  "Biology",
  "Biotechnology",
  "Building Technology",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Computer Engineering",
  "Computer Science",
  "Crop Science and Technology",
  "Cyber Security",
  "Dental Technology",
  "Electrical (Power Systems) Engineering",
  "Electronics Engineering",
  "Entrepreneurship and Innovation",
  "Environmental Health Science",
  "Environmental Management",
  "Environmental Management and Evaluation",
  "Environmental Management and Evaluation.", // Keeping both if specific variant requested
  "Fisheries and Aquaculture Technology",
  "Food Science and technology",
  "Forensic Science",
  "Forestry and Wildlife Technology",
  "Geology",
  "Human Anatomy",
  "Human Physiology",
  "Information Technology",
  "Logistics and Transport Technology",
  "Maritime Technology and Logistics",
  "Material and Metallurgical Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Microbiology",
  "Optometry",
  "Petroleum Engineering",
  "Physics",
  "Polymer and Textile Engineering",
  "Project Management Technology",
  "Prosthetics and Orthotics",
  "Public Health Technology",
  "Quantity Surveying",
  "Science Laboratory Technology",
  "Software Engineering",
  "Soil Science and Technology",
  "Statistics",
  "Supply Chain Management",
  "Surveying and Geoinformatics",
  "Telecommunications Engineering",
  "Urban and Regional Planning"
].sort((a, b) => a.localeCompare(b));
