import React from 'react';
import { Card } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Copy, FileText, Download, Code, Info, Terminal } from 'lucide-react';
import { toast } from 'sonner';
import { useTitle } from '../hooks/useTitle';

export default function PLXStandard() {
  useTitle('PLX Note Standard');

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success('Copied to clipboard');
  };

  const plxExample = `[H1] Introduction to PLX
[H2] What is .plx?
PLX (Pillara Extensible) is a human-readable and AI-friendly note format designed for the Pantheon Note Builder.

[MATH] E = mc^2

[LIST]
- Lightweight
- Structured
- Easily parsed

[ORDERED]
1. Define Content
2. Use Tags
3. Save as .plx

[TABLE]
| Feature | PLX Tag |
|---------|---------|
| Header  | [H1], [H2] |
| Math    | [MATH]  |
| Video   | [VIDEO] |

[VIDEO] https://www.youtube.com/watch?v=dQw4w9WgXcQ
`;

  return (
    <div className="max-w-4xl mx-auto py-8 px-4 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold tracking-tight text-amber-600 flex items-center gap-2">
          <FileText className="h-8 w-8" />
          PLX Note Standard
        </h1>
        <p className="text-muted-foreground text-lg">
          The Pillara Extensible (.plx) format is the official cross-platform standard for Pantheon notes.
        </p>
      </div>

      <Card className="p-6 bg-stone-50 border-stone-200">
        <div className="flex items-start gap-4">
          <div className="p-3 rounded-full bg-amber-100 text-amber-700">
            <Info className="h-6 w-6" />
          </div>
          <div className="space-y-4">
            <h2 className="text-xl font-semibold">How it works</h2>
            <p className="text-stone-600 leading-relaxed">
              PLX uses explicit block tags to define the structure of a note. It is designed to be easily generated by AI (like ChatGPT, Groq, or Claude) and perfectly parsed by the Pantheon system.
            </p>
            <div className="bg-white p-4 rounded-lg border border-stone-200 font-mono text-sm">
              <p className="text-amber-800 mb-2 font-bold uppercase tracking-widest text-[10px]">Important Rule:</p>
              <p className="text-stone-600 italic">"Save your content as a text file with the <b>.plx</b> extension."</p>
            </div>
          </div>
        </div>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="space-y-4">
          <h3 className="text-lg font-bold flex items-center gap-2">
            <Terminal className="h-5 w-5 text-amber-600" />
            Syntax Reference
          </h3>
          <div className="space-y-2">
            {[
              { tag: '[H1]', desc: 'Main Header (Heading 1)' },
              { tag: '[H2]', desc: 'Sub Header (Heading 2)' },
              { tag: '[MATH]', desc: 'LaTeX Mathematical Equation' },
              { tag: '[LIST]', desc: 'Bullet point list' },
              { tag: '[ORDERED]', desc: 'Numbered/Ordered list' },
              { tag: '[TABLE]', desc: 'Markdown-style table' },
              { tag: '[VIDEO]', desc: 'YouTube or Video URL' },
              { tag: '[DIAGRAM]', desc: 'Diagram or complex text block' },
            ].map((item) => (
              <div key={item.tag} className="flex items-center justify-between p-3 bg-white rounded-lg border border-stone-100 group hover:border-amber-200 transition-colors">
                <code className="text-amber-700 font-bold bg-amber-50 px-2 py-0.5 rounded">{item.tag}</code>
                <span className="text-sm text-stone-500">{item.desc}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="space-y-4">
          <h3 className="text-lg font-bold flex items-center gap-2">
            <Code className="h-5 w-5 text-amber-600" />
            Example Document
          </h3>
          <div className="relative group">
            <pre className="bg-stone-900 text-stone-100 p-4 rounded-xl text-xs overflow-x-auto h-[320px] leading-relaxed">
              {plxExample}
            </pre>
            <Button 
              variant="secondary" 
              size="sm" 
              className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity"
              onClick={() => copyToClipboard(plxExample)}
            >
              <Copy className="h-3 w-3 mr-2" />
              Copy
            </Button>
          </div>
        </div>
      </div>

      <Card className="p-8 border-dashed border-2 bg-amber-50/30 border-amber-200 flex flex-col items-center text-center space-y-4">
        <div className="p-4 rounded-full bg-white shadow-sm">
          <Download className="h-10 w-10 text-amber-600" />
        </div>
        <div className="max-w-md">
          <h3 className="text-xl font-bold">Share with your AI</h3>
          <p className="text-sm text-stone-500 mt-2">
            Copy the link to this page and give it to any AI. Tell it: 
            <span className="italic text-amber-700 font-medium block mt-2">
              "Generate a lecture summary for me using the Pantheon PLX standard found at this URL."
            </span>
          </p>
        </div>
        <Button 
          className="bg-amber-600 hover:bg-amber-700"
          onClick={() => copyToClipboard(window.location.origin + '/plx.txt')}
        >
          Copy Raw Standard URL
        </Button>
        <p className="text-[10px] text-stone-400">
          Raw version for terminal/AI: <a href="/plx.txt" className="underline">/plx.txt</a>
        </p>
      </Card>
    </div>
  );
}
