[package]
name = "pantheon-flux"
version = "1.0.0"
description = "Extracurricular wing of Pantheon"

[[modules]]
name = "web"
source = "dist"

[[services]]
name = "web"
module = "web"
public = true

[services.config]
port = 3000
protocol = "http"

[deploy]
domain = "flux.pantheon.com.ng"
